### ISSUE TITLE
Document UID Encoding Protocol and Collision Detection Corollaries

### ISSUE THREAD

**Issue by cabeese** [cabeese/crab-tracker#6]
## Background

Our UID encoding has morphed since the inception of the project, and we want to ensure that it is clearly documented for all parties going forward. Our protocol will be based on the ideas presented in Section 4.4 of the [RFC 1](https://github.com/cabeese/crab-tracker/blob/master/doc/rfc1/RFC1.pdf) document.

## TODOs

- [x] Decide on whether or not we'll redundantly encode ID information in the ping lengths and delay times of each signal.
- [x] Document the encoding protocol in general terms, explicitly stating which variables and functions are subject to change based on prototype testing.
- [x] Document the values and encoding functions (mentioned above) in a living document that will be updated as we prototype. Each iteration of the encoding and decoding software should comply with this spec.
