### ISSUE TITLE
Research possibility of encoding boolean value in transmissions

### ISSUE THREAD

**Issue by cabeese** [cabeese/crab-tracker#9]
# Background

Our client has requested that we look into adding the ability for a transmitter to broadcast some additional detail about the crab it is paired with. Specifically, Patrick is interested in attaching accelerometers to the tagged crabs so that we can determine if a given crab is "inert," perhaps because it has molted its shell or because it has died. We would encode this as an additional binary value in the transmission signal.

**Edit 2017-12-25:**
Note that some terminology used in this document is defined in RFC2, which currently lives on a different branch from the branch where work on this document is taking place. See the [`6-uid-encoding-documentation`](https://github.com/cabeese/crab-tracker/compare/6-uid-encoding-documentation) branch to read RFC2's glossary of terms.

# Requirements

We want to be able to encode both a UID and some binary value in each transmission without losing the work we've done to ensure that all collisions are detectable. Additionally, in the event that we decide not to include this feature in the final product, the changes made to the iCRAB protocol must not interfere with our original goals. That is, if we scrap this requirement, it should cost little or no extra work to continue on our original path.

# TODO

* [x] Create an RFC detailing the problem
* [x] Include potential solutions in the RFC
* [x] Solicit feedback on said solutions and decide on one
* [ ] Incorporate this solution into the iCRAB protocol definition

**Comment by cabeese** [comment]
Based on team discussions, we have decided to adopt "Method 4.2," in which we effectively double the number of IDs we encode and reserve half of them for use only when the boolean value is `true`. RFC-2 will be updated to reflect this and then these changes will be integrated into the official iCRAB protocol definition document.
